# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nba_stats_pb2 as nba__stats__pb2


class NbaStatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeNbaStats = channel.unary_stream(
                '/NbaStats/SubscribeNbaStats',
                request_serializer=nba__stats__pb2.NbaStatsSubscription.SerializeToString,
                response_deserializer=nba__stats__pb2.PlayerStatisticsResponse.FromString,
                )
        self.GetSeasonAverages = channel.unary_unary(
                '/NbaStats/GetSeasonAverages',
                request_serializer=nba__stats__pb2.SeasonAveragesRequest.SerializeToString,
                response_deserializer=nba__stats__pb2.SeasonAveragesResponse.FromString,
                )


class NbaStatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeNbaStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeasonAverages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NbaStatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeNbaStats': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeNbaStats,
                    request_deserializer=nba__stats__pb2.NbaStatsSubscription.FromString,
                    response_serializer=nba__stats__pb2.PlayerStatisticsResponse.SerializeToString,
            ),
            'GetSeasonAverages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeasonAverages,
                    request_deserializer=nba__stats__pb2.SeasonAveragesRequest.FromString,
                    response_serializer=nba__stats__pb2.SeasonAveragesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NbaStats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NbaStats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeNbaStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/NbaStats/SubscribeNbaStats',
            nba__stats__pb2.NbaStatsSubscription.SerializeToString,
            nba__stats__pb2.PlayerStatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeasonAverages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NbaStats/GetSeasonAverages',
            nba__stats__pb2.SeasonAveragesRequest.SerializeToString,
            nba__stats__pb2.SeasonAveragesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
