//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `actions.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.agh.edu.pl.actions;

/** @hidden */
public class _BoosterPrxI extends com.zeroc.Ice._ObjectPrxI implements BoosterPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
